//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        public string ID_S { get; set; }
        public string ID_NXB { get; set; }
        public string ID_TG { get; set; }
        public string ID_TL { get; set; }
        public string Ten { get; set; }
        public byte[] BiaSach { get; set; }
        public Nullable<System.DateTime> Ngay_XuatBan { get; set; }
        public Nullable<double> KichThuoc { get; set; }
        public Nullable<int> SoTrang { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaBia { get; set; }
        public string ChiTiet { get; set; }
        public string ID_NCC { get; set; }
    
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual NHA_XUAT_BAN NHA_XUAT_BAN { get; set; }
        public virtual TAC_GIA TAC_GIA { get; set; }
        public virtual THE_LOAI THE_LOAI { get; set; }
    }
}
